### ISSUE TITLE
some 🐛 related to merra2 codes

### ISSUE THREAD

**Issue by chiachl6** [tsutterley/model-harmonics#15]
1. "merra_smb_harmonics.py", line 141, 
if np.any(MASKS): ---> if bool(MASKS)

2."merra_smb_harmonics.py", line 407
merra_Ylms.month[t] =...  ---> merra_Ylms.month =...

3.after running "merra_smb_harmonics.py", it'll gives out 2 files (MERRA2_401_tavgM_2d_SMB_CLM_L60_225.nc & MERRA2_400_tavgM_2d_SMB_CLM_L60_225) for 2020/09 (the reprocessed month). Need  to manually delete the 400 one. (and the path in index file)

**Comment by tsutterley** [comment]
I think i have everything fixed up.  I added a warning in [merra_smb_harmonics](https://github.com/tsutterley/model-harmonics/blob/main/SMB/merra_smb_harmonics.py#L200) if there are old files found.
