### ISSUE TITLE
Can you add 1 more variable in --product this code?

### ISSUE THREAD

**Issue by chiachl6** [tsutterley/model-harmonics#21]
Hey Tyler, could you add 1 more variable in --product (i.e. MERRA2 hybrid product to calculate) in /model-harmonics/SMB/merra_hybrid_regrid.py? 
I need "density". So either add firn height anomaly (h_a) in --product options and I can calculate density myself, or add density option is good. Many thanks
*Now I think about it, maybe adding h_a is better so I have more flexibility

**Comment by tsutterley** [comment]
Done :)
